services:
  elvara-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: elvara_sepsis_api
    ports:
      - "8080:8000"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./monitoring:/app/monitoring
      - ./models:/app/models
      - ./data:/app/data
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  prometheus:
    build:
      context: .
      dockerfile: monitoring/Dockerfile.prometheus
    container_name: elvara_prometheus
    ports:
      - "9090:9090"
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: elvara_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
